---
auth:
  authType: "NONE"
  rememberUsers: true
  rememberMeValidityDays: 14
  authHeader: null
  authHeaderIpRanges: []
  restrictAdmin: false
  restrictDetailsDl: false
  restrictIndexerSelection: false
  restrictSearch: false
  restrictStats: false
  allowApiStats: true
  users: []
categoriesConfig:
  enableCategorySizes: true
  categories:
  - name: "Anime"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "5070"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 3000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "ANIME"
  - name: "Audio"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 2000
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Audiobook"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 1000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "AUDIOBOOK"
  - name: "Comic"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "7030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 250
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "COMIC"
  - name: "Console"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "1000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 40000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Ebook"
    mayBeSelected: true
    searchType: "BOOK"
    newznabCategories:
    - "7020"
    - "8010"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 100
    minSizePreset: null
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "EBOOK"
  - name: "FLAC"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3040"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 2000
    minSizePreset: 10
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "MP3"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3010"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 500
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - "2000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 20000
    minSizePreset: 500
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies HD"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - "2040"
    - "2050"
    - "2060"
    - "2070"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 20000
    minSizePreset: 3000
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies SD"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - "2030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 3000
    minSizePreset: 500
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "PC"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "4000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 50000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - "5000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 5000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV HD"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - "5040"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 4500
    minSizePreset: 300
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV SD"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - "5030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 1000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "XXX"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "6000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 10000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  defaultCategory: "All"
downloading:
  downloaders: []
  saveTorrentsTo: null
  saveNzbsTo: null
  sendMagnetLinks: true
  updateStatuses: true
  showDownloaderStatus: true
  nzbAccessType: "PROXY"
  fallbackForFailed: "BOTH"
indexers: []
main:
  configVersion: 14
  host: "0.0.0.0"
  port: 5076
  urlBase: "/"
  proxyType: "NONE"
  proxyHost: null
  proxyPort: 1080
  proxyIgnoreLocal: true
  proxyIgnoreDomains: []
  proxyUsername: null
  proxyPassword: null
  backupFolder: "backup"
  backupEveryXDays: 7
  backupBeforeUpdate: true
  deleteBackupsAfterWeeks: 4
  keepHistory: true
  keepStatsForWeeks: null
  keepHistoryForWeeks: null
  ssl: false
  sslKeyStore: null
  sslKeyStorePassword: null
  verifySsl: true
  disableSslLocally: false
  sniDisabledFor:
  - "nzbgeek.info"
  verifySslDisabledFor: []
  updateAutomatically: false
  updateToPrereleases: false
  updateCheckEnabled: true
  showUpdateBannerOnDocker: true
  showNews: true
  startupBrowser: true
  welcomeShown: true
  theme: "grey"
  databaseCompactTime: 15000
  databaseRetentionTime: 1000
  databaseWriteDelay: 5000
  apiKey: "HDhotQ194LtdvNiPxbCtX46j"
  dereferer: "http://www.dereferer.org/?$s"
  instanceCounterDownloaded: true
  repositoryBase: "https://github.com/theotherp"
  shutdownForRestart: false
  useCsrf: true
  xmx: 256
  logging:
    consolelevel: "INFO"
    historyUserInfoType: "NONE"
    logIpAddresses: true
    mapIpToHost: true
    logGc: false
    logMaxHistory: 30
    logfilelevel: "INFO"
    logUsername: false
    markersToLog: []
searching:
  applyRestrictions: "NONE"
  coverSize: 128
  globalCacheTimeMinutes: null
  duplicateAgeThreshold: 2.0
  duplicateSizeThresholdInPercent: 1.0
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: null
  forbiddenWords: []
  alwaysConvertIds: "NONE"
  generateQueries: "INTERNAL"
  generateQueriesFormat: "TITLE"
  idFallbackToQueryGeneration: "NONE"
  ignorePassworded: false
  ignoreTemporarilyDisabled: false
  ignoreLoadLimitingForInternalSearches: false
  keepSearchResultsForDays: 14
  language: "en_US.UTF-8"
  languagesToKeep: []
  loadAllCachedOnInternal: true
  loadLimitInternal: 100
  maxAge: null
  minSeeders: null
  removeTrailing:
  - ".mp4"
  - ".mkv"
  - ".subs"
  - ".REPOST"
  - "repost"
  - "~DG~"
  - ".DG"
  - "-DG"
  - "-1"
  - ".1"
  - "(1)"
  - "ReUp"
  - "ReUp2"
  - "-RP"
  - "-AsRequested"
  - "-Obfuscated"
  - "-Scrambled"
  - "-Chamele0n"
  - "-BUYMORE"
  - "-[TRP]"
  - "-DG"
  - ".par2"
  - ".part01"
  - "part01.rar"
  - ".part02.rar"
  - ".jpg"
  - "[rartv]"
  - "[rarbg]"
  - "[eztv]"
  - "English"
  - "Korean"
  - "Spanish"
  - "French"
  - "German"
  - "Italian"
  - "Danish"
  - "Dutch"
  - "Japanese"
  - "Cantonese"
  - "Mandarin"
  - "Russian"
  - "Polish"
  - "Vietnamese"
  - "Swedish"
  - "Norwegian"
  - "Finnish"
  - "Turkish"
  - "Portuguese"
  - "Flemish"
  - "Greek"
  - "Hungarian"
  requiredRegex: null
  requiredWords: []
  sendTorznabCategories: true
  showQuickFilterButtons: true
  timeout: 20
  transformNewznabCategories: true
  userAgent: "NZBHydra2"
  userAgents:
  - "Mozilla"
  - "Sonarr"
  - "Radarr"
  - "CouchPotato"
  - "LazyLibrarian"
  - "NZBGet"
  - "sabNZBd"
  useOriginalCategories: false
  wrapApiErrors: false
genericStorage:
  outdatedWrapperDetected: "false"
  FirstStart: ""
